module.exports = {
  dashboard: '/app',
  login: '/login',
  signup: '/signup',
  market: '#',
  email: '/app/pages/email',
  profile: '/app/pages/user-profile',
  calendar: '/app/pages/calendar',
  twitter: '#',
  github: '#',
  pinterest: '#',
  linkedin: '#',
  buy: '#',
  admins: '/itdashboard/principals',
  bursars: '/itdashboard/bursars',
  teachers: '/itdashboard/teachers',
  parents: '/itdashboard/parents',
  students: '/itdashboard/students',
  ongoingcourses: '/itdashboard/ongoingcourses',
  finishedcourses: '/itdashboard/finishedcourses',
  inactivecourses: '/itdashboard/inactivecourses',
  upcomingcourses: '/itdashboard/upcomingcourses',
  authors: '/itdashboard/authors',
  publishers: '/itdashboard/publishers',
  cities: '/itdashboard/cities',
  approved: '/itdashboard/approved-admissions',
  pending: '/itdashboard/pending-admissions',
  meeting: '/itdashboard/meeting-admissions',
  rejected: '/itdashboard/rejected-admissions',

  oncourses: '/teacherdashboard/ongoingcourses',
  finishcourses: '/teacherdashboard/finishedcourses',
  inactivecourse: '/teacherdashboard/inactivecourses',
  upcomingcourse: '/teacherdashboard/upcomingcourses',
  author: '/teacherdashboard/authors',
  publisher: '/teacherdashboard/publishers',
  city: '/teacherdashboard/cities',

  ongoingcourse: '/studentdashboard/ongoingcourses',
  upcourses: '/studentdashboard/upcomingcourses',
  authorz: '/studentdashboard/authors',
  publisherz: '/studentdashboard/publishers',
  citiez: '/studentdashboard/cities',
};
