# Generated by Django 3.0.7 on 2020-12-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201227_0837'),
        ('fees', '0002_auto_20201227_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesconfig',
            old_name='include_units_in_sales_invoice',
            new_name='include_units_in_fees_invoice',
        ),
        migrations.RemoveField(
            model_name='feesconfig',
            name='sales_tax',
        ),
        migrations.AddField(
            model_name='feesconfig',
            name='tax',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tax'),
        ),
    ]
