# Generated by Django 3.0.7 on 2020-12-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('fees', '0003_auto_20201227_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='draft',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myinvoices', to='people.Student'),
        ),
    ]
