# Generated by Django 3.1.4 on 2020-12-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('grade', models.CharField(max_length=68)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=68)),
                ('max_population', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('year', models.CharField(max_length=68)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive'), ('dormant', 'Dormant'), ('aged', 'Aged')], max_length=68)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
