# Generated by Django 3.1.5 on 2021-02-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('grade', models.CharField(max_length=68)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=68)),
                ('max_population', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('year', models.CharField(max_length=68)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive'), ('dormant', 'Dormant'), ('aged', 'Aged')], max_length=68)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enroll', 'ENROLLED'), ('disenroll', 'DISENROLLED')], default='enroll', max_length=200)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('enr_klass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klasses.studentclass')),
            ],
        ),
    ]
