# Generated by Django 3.1.5 on 2021-02-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_auto_20210201_1054'),
        ('people', '0001_initial'),
        ('klasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='stdnt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='class_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.teacherprofile'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='klasses.stream'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='students',
            field=models.ManyToManyField(related_name='klasses', through='klasses.StudentEnrollment', to='people.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='subjects',
            field=models.ManyToManyField(through='curriculum.KlassStudiedSubject', to='curriculum.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('stdnt', 'enr_klass')},
        ),
    ]
