# Generated by Django 3.0.7 on 2021-01-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klasses', '0001_initial'),
        ('curriculum', '0002_auto_20210125_0958'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='class_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='klasses.Stream'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='subjects',
            field=models.ManyToManyField(through='curriculum.KlassStudiedSubject', to='curriculum.Subject'),
        ),
    ]
