# Generated by Django 3.1.4 on 2020-12-27 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klasses', '0001_initial'),
        ('curriculum', '0002_auto_20201227_0837'),
        ('people', '0001_initial'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.staffuser'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klasses', to='setup.institution'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='klasses.stream'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='subjects',
            field=models.ManyToManyField(through='curriculum.KlassStudiedSubject', to='curriculum.Subject'),
        ),
    ]
