# Generated by Django 3.0.7 on 2020-11-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('klasses', '0001_initial'),
        ('curriculum', '0002_auto_20201126_1034'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='stdnt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.Student'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.StaffUser'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klasses', to='setup.Institution'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='klasses.Stream'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='students',
            field=models.ManyToManyField(through='klasses.StudentEnrollment', to='people.Student'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='subjects',
            field=models.ManyToManyField(through='curriculum.KlassStudiedSubject', to='curriculum.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('stdnt', 'enr_klass')},
        ),
    ]
