# Generated by Django 3.0.7 on 2020-12-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('klasses', '0002_auto_20201227_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='class_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.StaffUser'),
        ),
    ]
