# Generated by Django 3.1.5 on 2021-01-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210125_1401'),
        ('klasses', '0002_auto_20210125_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enroll', 'ENROLLED'), ('disenroll', 'DISENROLLED')], default='enroll', max_length=200)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('enr_klass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klasses.studentclass')),
                ('stdnt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.studentprofile')),
            ],
            options={
                'unique_together': {('stdnt', 'enr_klass')},
            },
        ),
        migrations.AddField(
            model_name='studentclass',
            name='students',
            field=models.ManyToManyField(related_name='klasses', through='klasses.StudentEnrollment', to='people.StudentProfile'),
        ),
    ]
