# Generated by Django 3.0.7 on 2020-12-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0003_auto_20201227_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='institution',
        ),
    ]
