# Generated by Django 3.2.4 on 2021-08-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=234)),
                ('author', models.CharField(max_length=234)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('content', models.TextField()),
                ('published_date', models.DateField()),
            ],
        ),
    ]
