# Generated by Django 3.0.7 on 2020-11-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHeadOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=68)),
                ('location', models.CharField(max_length=68)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=68)),
                ('type', models.CharField(choices=[('school', 'SCHOOL'), ('college', 'COLLEGE')], max_length=68)),
                ('status', models.CharField(choices=[('day', 'DAY'), ('boarding', 'BOARDING')], max_length=68)),
                ('address', models.TextField(max_length=68)),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('school_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_info')),
                ('head_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='setup.SchoolHeadOffice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
