export const EDIT_COURSE_ADVERT = 'EDIT_COURSE_ADVERT';
export const GET_COURSE_ADVERTS_START = 'GET_COURSE_ADVERTS_START';
export const GET_COURSE_ADVERTS_SUCCESS = 'GET_COURSE_ADVERTS_SUCCESS';
export const GET_COURSE_ADVERTS_FAIL = 'GET_COURSE_ADVERTS_FAIL';
export const GET_COURSE_ADVERT_START = 'GET_COURSE_ADVERT_START';
export const GET_COURSE_ADVERT_SUCCESS = 'GET_COURSE_ADVERT_SUCCESS';
export const GET_COURSE_ADVERT_FAIL = 'GET_COURSE_ADVERT_FAIL';
export const CREATE_COURSE_ADVERT_START = 'CREATE_COURSE_ADVERT_START';
export const CREATE_COURSE_ADVERT_SUCCESS = 'CREATE_COURSE_ADVERT_SUCCESS';
export const CREATE_COURSE_ADVERT_FAIL = 'CREATE_COURSE_ADVERT_FAIL';


export const GET_UPCOMING_OFFERED_COURSES_START = 'GET_UPCOMING_OFFERED_COURSES_START';
export const GET_UPCOMING_OFFERED_COURSES_SUCCESS = 'GET_UPCOMING_OFFERED_COURSES_SUCCESS';
export const GET_UPCOMING_OFFERED_COURSES_FAIL = 'GET_UPCOMING_OFFERED_COURSES_FAIL';
export const GET_UPCOMING_OFFERED_COURSE_START = 'GET_UPCOMING_OFFERED_COURSE_START';
export const GET_UPCOMING_OFFERED_COURSE_SUCCESS = 'GET_UPCOMING_OFFERED_COURSE_SUCCESS';
export const GET_UPCOMING_OFFERED_COURSE_FAIL = 'GET_UPCOMING_OFFERED_COURSE_FAIL';
export const ADD_UPCOMING_OFFERED_COURSE_START = 'ADD_UPCOMING_OFFERED_COURSE_START';
export const ADD_UPCOMING_OFFERED_COURSE_SUCCESS = 'ADD_UPCOMING_OFFERED_COURSE_SUCCESS';
export const ADD_UPCOMING_OFFERED_COURSE_FAIL = 'ADD_UPCOMING_OFFERED_COURSE_FAIL';

export const GET_ONGOING_OFFERED_COURSES_START = 'GET_ONGOING_OFFERED_COURSES_START';
export const GET_ONGOING_OFFERED_COURSES_SUCCESS = 'GET_ONGOING_OFFERED_COURSES_SUCCESS';
export const GET_ONGOING_OFFERED_COURSES_FAIL = 'GET_ONGOING_OFFERED_COURSES_FAIL';
export const GET_ONGOING_OFFERED_COURSE_START = 'GET_ONGOING_OFFERED_COURSE_START';
export const GET_ONGOING_OFFERED_COURSE_SUCCESS = 'GET_ONGOING_OFFERED_COURSE_SUCCESS';
export const GET_ONGOING_OFFERED_COURSE_FAIL = 'GET_ONGOING_OFFERED_COURSE_FAIL';
export const ADD_ONGOING_OFFERED_COURSE_START = 'ADD_ONGOING_OFFERED_COURSE_START';
export const ADD_ONGOING_OFFERED_COURSE_SUCCESS = 'ADD_ONGOING_OFFERED_COURSE_SUCCESS';
export const ADD_ONGOING_OFFERED_COURSE_FAIL = 'ADD_ONGOING_OFFERED_COURSE_FAIL';

export const GET_COURSE_MODULES_START = 'GET_COURSE_MODULES_START';
export const GET_COURSE_MODULES_SUCCESS = 'GET_COURSE_MODULES_SUCCESS';
export const GET_COURSE_MODULES_FAIL = 'GET_COURSE_MODULES_FAIL';
export const ADD_COURSE_MODULE_START = 'ADD_COURSE_MODULE_START';
export const ADD_COURSE_MODULE_SUCCESS = 'ADD_COURSE_MODULE_SUCCESS';
export const ADD_COURSE_MODULE_FAIL = 'ADD_COURSE_MODULE_FAIL';

export const GET_STUDENT_EXIT_PROFILES_START = 'GET_STUDENT_EXIT_PROFILES_START';
export const GET_STUDENT_EXIT_PROFILES_SUCCESS = 'GET_STUDENT_EXIT_PROFILES_SUCCESS';
export const GET_STUDENT_EXIT_PROFILES_FAIL = 'GET_STUDENT_EXIT_PROFILES_FAIL';
export const ADD_STUDENT_EXIT_PROFILE_START = 'ADD_STUDENT_EXIT_PROFILE_START';
export const ADD_STUDENT_EXIT_PROFILE_SUCCESS = 'ADD_STUDENT_EXIT_PROFILE_SUCCESS';
export const ADD_STUDENT_EXIT_PROFILE_FAIL = 'ADD_STUDENT_EXIT_PROFILE_FAIL';

export const GET_OFFERED_COURSE_OBJECTIVES_START = 'GET_OFFERED_COURSE_OBJECTIVES_START';
export const GET_OFFERED_COURSE_OBJECTIVES_SUCCESS = 'GET_OFFERED_COURSE_OBJECTIVES_SUCCESS';
export const GET_OFFERED_COURSE_OBJECTIVES_FAIL = 'GET_OFFERED_COURSE_OBJECTIVES_FAIL';
export const ADD_OFFERED_COURSE_OBJECTIVE_START = 'ADD_OFFERED_COURSE_OBJECTIVE_START';
export const ADD_OFFERED_COURSE_OBJECTIVE_SUCCESS = 'ADD_OFFERED_COURSE_OBJECTIVE_SUCCESS';
export const ADD_OFFERED_COURSE_OBJECTIVE_FAIL = 'ADD_OFFERED_COURSE_OBJECTIVE_FAIL';
