export const ADD_ATTENDANCE = 'ADD_ATTENDANCE';
export const GET_ATTENDANCES = 'GET_ATTENDANCES';
export const DELETE_ATTENDANCE = 'DELETE_ATTENDANCE';
export const GET_ATTENDANCE = 'GET_ATTENDANCE';
export const EDIT_ATTENDANCE = 'EDIT_ATTENDANCE';
export const GET_STUDENT_ATTENDANCES = 'GET_STUDENT_ATTENDANCES';

export const ADD_ATTENDANCE_RECORD = 'ADD_ATTENDANCE_RECORD';
export const GET_ATTENDANCE_RECORDS = 'GET_ATTENDANCE_RECORDS';
export const EDIT_ATTENDANCE_RECORD = 'EDIT_ATTENDANCE_RECORD';
