export const ADD_ATTENDANCE = 'ADD_ATTENDANCE';
export const GET_ATTENDANCES = 'GET_ATTENDANCES';
export const DELETE_ATTENDANCE = 'DELETE_ATTENDANCE';
export const GET_ATTENDANCE = 'GET_ATTENDANCE';
export const EDIT_ATTENDANCE = 'EDIT_ATTENDANCE';
export const GET_STUDENT_ATTENDANCES = 'GET_STUDENT_ATTENDANCES';