export const ADD_ATTENDANCE = 'ADD_ATTENDANCE';
export const GET_ATTENDANCES = 'GET_ATTENDANCES';
export const DELETE_ATTENDANCE = 'DELETE_ATTENDANCE';
export const GET_ATTENDANCE = 'GET_ATTENDANCE';
export const EDIT_ATTENDANCE = 'EDIT_ATTENDANCE';
export const GET_STUDENT_ATTENDANCES = 'GET_STUDENT_ATTENDANCES';

export const ADD_ATTENDANCE_RECORD = 'ADD_ATTENDANCE_RECORD';
export const GET_ATTENDANCE_RECORDS = 'GET_ATTENDANCE_RECORDS';
export const EDIT_ATTENDANCE_RECORD = 'EDIT_ATTENDANCE_RECORD';
export const ADD_TEACHER_ATTENDANCE = 'ADD_TEACHER_ATTENDANCE';
export const GET_STUDENT_ATTENDANCE_RECORDS = 'GET_STUDENT_ATTENDANCE_RECORDS';

export const GET_ATTENDANCES_START = 'GET_ATTENDANCES_START';
export const GET_ATTENDANCES_SUCCESS = 'GET_ATTENDANCES_SUCCESS';
export const GET_ATTENDANCES_FAIL = 'GET_ATTENDANCES_FAIL';
export const GET_ATTENDANCE_RECORDS_START = 'GET_ATTENDANCE_RECORDS_START';
export const GET_ATTENDANCE_RECORDS_SUCCESS = 'GET_ATTENDANCE_RECORDS_SUCCESS';
export const GET_ATTENDANCE_RECORDS_FAIL = 'GET_ATTENDANCE_RECORDS_FAIL';
export const CREATE_ATTENDANCE_RECORD_START = 'CREATE_ATTENDANCE_RECORD_START';
export const CREATE_ATTENDANCE_RECORD_SUCCESS = 'CREATE_ATTENDANCE_RECORD_SUCCESS';
export const CREATE_ATTENDANCE_RECORD_FAIL = 'CREATE_ATTENDANCE_RECORD_FAIL';
export const CREATE_ATTENDANCE_START = 'CREATE_ATTENDANCE_START';
export const CREATE_ATTENDANCE_SUCCESS = 'CREATE_ATTENDANCE_SUCCESS';
export const CREATE_ATTENDANCE_FAIL = 'CREATE_ATTENDANCE_FAIL';