export const ADD_CLASS = 'ADD_CLASS';
export const GET_CLASSES = 'GET_CLASSES';
export const GET_CLASS = 'GET_CLASS';
export const EDIT_CLASS = 'EDIT_CLASS';
export const ADD_STREAM = 'ADD_STREAM';
export const GET_STREAMS = 'GET_STREAMS';
export const EDIT_STREAM = 'EDIT_STREAM';

export const GET_CLASS_SUBJECTS = 'GET_CLASS_SUBJECTS';
export const ADD_CLASS_SUBJECT = 'ADD_CLASS_SUBJECT';
export const EDIT_CLASS_SUBJECT = 'EDIT_CLASS_SUBJECT';
export const GET_CLASS_STUDENTS = 'GET_CLASS_STUDENTS';

export const GET_CLASS_SUBJECT ='GET_CLASS_SUBJECT';

export const GET_CLASS_STUDENT ='GET_CLASS_STUDENT';

export const ADD_ENROLLMENT ='ADD_ENROLLMENT';
export const GET_ENROLLMENTS ='GET_ENROLLMENTS';
export const GET_STUDY_MODE_CHOICES ='GET_STUDY_MODE_CHOICES';
export const EDIT_ENROLLMENT ='EDIT_ENROLLMENT';

export const GET_UNENROLLED_STUDENTS = 'GET_UNENROLLED_STUDENTS';
