export const ADD_CURRICULUM = 'ADD_CURRICULUM';
export const GET_CURRICULUMS = 'GET_CURRICULUMS';
export const DELETE_CURRICULUM = 'DELETE_CURRICULUM';
export const GET_CURRICULUM = 'GET_CURRICULUM';
export const EDIT_CURRICULUM = 'EDIT_CURRICULUM';

export const ADD_SUBJECT = 'ADD_SUBJECT';
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const GET_SUBJECT = 'GET_SUBJECT';
export const EDIT_SUBJECT = 'EDIT_SUBJECT';


