export const GET_UNREAD_NOTIFICATIONS_START = 'GET_UNREAD_NOTIFICATIONS_START';
export const GET_UNREAD_NOTIFICATIONS_SUCCESS = 'GET_UNREAD_NOTIFICATIONS_SUCCESS';
export const GET_UNREAD_NOTIFICATIONS_FAIL = 'GET_UNREAD_NOTIFICATIONS_FAIL';
export const GET_UNREAD_NOTIFICATION_START = 'GET_UNREAD_NOTIFICATION_START';
export const GET_UNREAD_NOTIFICATION_SUCCESS = 'GET_UNREAD_NOTIFICATION_SUCCESS';
export const GET_UNREAD_NOTIFICATION_FAIL = 'GET_UNREAD_NOTIFICATION_FAIL';
export const GET_READ_NOTIFICATIONS_START = 'GET_READ_NOTIFICATIONS_START';
export const GET_READ_NOTIFICATIONS_SUCCESS = 'GET_READ_NOTIFICATIONS_SUCCESS';
export const GET_READ_NOTIFICATIONS_FAIL = 'GET_READ_NOTIFICATIONS_FAIL';
export const GET_READ_NOTIFICATION_START = 'GET_READ_NOTIFICATION_START';
export const GET_READ_NOTIFICATION_SUCCESS = 'GET_READ_NOTIFICATION_SUCCESS';
export const GET_READ_NOTIFICATION_FAIL = 'GET_READ_NOTIFICATION_FAIL';

export const READ_NOTIFICATION_START = 'READ_NOTIFICATION_START';
export const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS';
export const READ_NOTIFICATION_FAIL = 'READ_NOTIFICATION_FAIL';