export const GET_ASSIGNED_CLOSED_TICKETS_START = 'GET_ASSIGNED_CLOSED_TICKETS_START';
export const GET_ASSIGNED_CLOSED_TICKETS_SUCCESS = 'GET_ASSIGNED_CLOSED_TICKETS_SUCCESS';
export const GET_ASSIGNED_CLOSED_TICKETS_FAIL = 'GET_ASSIGNED_CLOSED_TICKETS_FAIL';
export const GET_ASSIGNED_CLOSED_TICKET_START = 'GET_ASSIGNED_CLOSED_TICKET_START';
export const GET_ASSIGNED_CLOSED_TICKET_SUCCESS = 'GET_ASSIGNED_CLOSED_TICKET_SUCCESS';
export const GET_ASSIGNED_CLOSED_TICKET_FAIL = 'GET_ASSIGNED_CLOSED_TICKET_FAIL';
export const GET_ASSIGNED_OPEN_TICKETS_START = 'GET_ASSIGNED_OPEN_TICKETS_START';
export const GET_ASSIGNED_OPEN_TICKETS_SUCCESS = 'GET_ASSIGNED_OPEN_TICKETS_SUCCESS';
export const GET_ASSIGNED_OPEN_TICKETS_FAIL = 'GET_ASSIGNED_OPEN_TICKETS_FAIL';
export const GET_ASSIGNED_OPEN_TICKET_START = 'GET_ASSIGNED_OPEN_TICKET_START';
export const GET_ASSIGNED_OPEN_TICKET_SUCCESS = 'GET_ASSIGNED_OPEN_TICKET_SUCCESS';
export const GET_ASSIGNED_OPEN_TICKET_FAIL = 'GET_ASSIGNED_OPEN_TICKET_FAIL';
export const GET_ASSIGNED_REOPENED_TICKETS_START = 'GET_ASSIGNED_REOPENED_TICKETS_START';
export const GET_ASSIGNED_REOPENED_TICKETS_SUCCESS = 'GET_ASSIGNED_REOPENED_TICKETS_SUCCESS';
export const GET_ASSIGNED_REOPENED_TICKETS_FAIL = 'GET_ASSIGNED_REOPENED_TICKETS_FAIL';
export const GET_ASSIGNED_REOPENED_TICKET_START = 'GET_ASSIGNED_REOPENED_TICKET_START';
export const GET_ASSIGNED_REOPENED_TICKET_SUCCESS = 'GET_ASSIGNED_REOPENED_TICKET_SUCCESS';
export const GET_ASSIGNED_REOPENED_TICKET_FAIL = 'GET_ASSIGNED_REOPENED_TICKET_FAIL';
export const GET_CLOSED_TICKETS_START = 'GET_CLOSED_TICKETS_START';
export const GET_CLOSED_TICKETS_SUCCESS = 'GET_CLOSED_TICKETS_SUCCESS';
export const GET_CLOSED_TICKETS_FAIL = 'GET_CLOSED_TICKETS_FAIL';
export const GET_CLOSED_TICKET_START = 'GET_CLOSED_TICKET_START';
export const GET_CLOSED_TICKET_SUCCESS = 'GET_CLOSED_TICKET_SUCCESS';
export const GET_CLOSED_TICKET_FAIL = 'GET_CLOSED_TICKET_FAIL';

export const GET_COMMENTS_START = 'GET_COMMENTS_START';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';
export const CREATE_COMMENT_START = 'CREATE_COMMENT_START';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';
export const GET_COMMENT_START = 'GET_COMMENT_START';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAIL = 'GET_COMMENT_FAIL';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const GET_CUSTOMER_CLOSED_TICKETS_START = 'GET_CUSTOMER_CLOSED_TICKETS_START';
export const GET_CUSTOMER_CLOSED_TICKETS_SUCCESS = 'GET_CUSTOMER_CLOSED_TICKETS_SUCCESS';
export const GET_CUSTOMER_CLOSED_TICKETS_FAIL = 'GET_CUSTOMER_CLOSED_TICKETS_FAIL';
export const GET_CUSTOMER_CLOSED_TICKET_START = 'GET_CUSTOMER_CLOSED_TICKET_START';
export const GET_CUSTOMER_CLOSED_TICKET_SUCCESS = 'GET_CUSTOMER_CLOSED_TICKET_SUCCESS';
export const GET_CUSTOMER_CLOSED_TICKET_FAIL = 'GET_CUSTOMER_CLOSED_TICKET_FAIL';
export const GET_CUSTOMER_OPEN_TICKETS_START = 'GET_CUSTOMER_OPEN_TICKETS_START';
export const GET_CUSTOMER_OPEN_TICKETS_SUCCESS = 'GET_CUSTOMER_OPEN_TICKETS_SUCCESS';
export const GET_CUSTOMER_OPEN_TICKETS_FAIL = 'GET_CUSTOMER_OPEN_TICKETS_FAIL';
export const CREATE_CUSTOMER_OPEN_TICKET_START = 'CREATE_CUSTOMER_OPEN_TICKET_START';
export const CREATE_CUSTOMER_OPEN_TICKET_SUCCESS = 'CREATE_CUSTOMER_OPEN_TICKET_SUCCESS';
export const CREATE_CUSTOMER_OPEN_TICKET_FAIL = 'CREATE_CUSTOMER_OPEN_TICKET_FAIL';
export const GET_CUSTOMER_OPEN_TICKET_START = 'GET_CUSTOMER_OPEN_TICKET_START';
export const GET_CUSTOMER_OPEN_TICKET_SUCCESS = 'GET_CUSTOMER_OPEN_TICKET_SUCCESS';
export const GET_CUSTOMER_OPEN_TICKET_FAIL = 'GET_CUSTOMER_OPEN_TICKET_FAIL';
export const EDIT_CUSTOMER_OPEN_TICKET = 'EDIT_CUSTOMER_OPEN_TICKET';
export const GET_CUSTOMER_REOPENED_TICKETS_START = 'GET_CUSTOMER_REOPENED_TICKETS_START';
export const GET_CUSTOMER_REOPENED_TICKETS_SUCCESS = 'GET_CUSTOMER_REOPENED_TICKETS_SUCCESS';
export const GET_CUSTOMER_REOPENED_TICKETS_FAIL = 'GET_CUSTOMER_REOPENED_TICKETS_FAIL';
export const GET_CUSTOMER_REOPENED_TICKET_START = 'GET_CUSTOMER_REOPENED_TICKET_START';
export const GET_CUSTOMER_REOPENED_TICKET_SUCCESS = 'GET_CUSTOMER_REOPENED_TICKET_SUCCESS';
export const GET_CUSTOMER_REOPENED_TICKET_FAIL = 'GET_CUSTOMER_REOPENED_TICKET_FAIL';
export const GET_OPEN_TICKETS_START = 'GET_OPEN_TICKETS_START';
export const GET_OPEN_TICKETS_SUCCESS = 'GET_OPEN_TICKETS_SUCCESS';
export const GET_OPEN_TICKETS_FAIL = 'GET_OPEN_TICKETS_FAIL';
export const GET_OPEN_TICKET_START = 'GET_OPEN_TICKET_START';
export const GET_OPEN_TICKET_SUCCESS = 'GET_OPEN_TICKET_SUCCESS';
export const GET_OPEN_TICKET_FAIL = 'GET_OPEN_TICKET_FAIL';
export const GET_REOPENED_TICKETS_START = 'GET_REOPENED_TICKETS_START';
export const GET_REOPENED_TICKETS_SUCCESS = 'GET_REOPENED_TICKETS_SUCCESS';
export const GET_REOPENED_TICKETS_FAIL = 'GET_REOPENED_TICKETS_FAIL';
export const GET_REOPENED_TICKET_START = 'GET_REOPENED_TICKET_START';
export const GET_REOPENED_TICKET_SUCCESS = 'GET_REOPENED_TICKET_SUCCESS';
export const GET_REOPENED_TICKET_FAIL = 'GET_REOPENED_TICKET_FAIL';

export const CLOSE_TICKET_START = 'CLOSE_TICKET_START';
export const CLOSE_TICKET_SUCCESS = 'CLOSE_TICKET_SUCCESS';
export const CLOSE_TICKET_FAIL = 'CLOSE_TICKET_FAIL';
export const CLOSE_REOPENED_TICKET_START = 'CLOSE_REOPENED_TICKET_START';
export const CLOSE_REOPENED_TICKET_SUCCESS = 'CLOSE_REOPENED_TICKET_SUCCESS';
export const CLOSE_REOPENED_TICKET_FAIL = 'CLOSE_REOPENED_TICKET_FAIL';
export const REOPEN_TICKET_START = 'REOPEN_TICKET_START';
export const REOPEN_TICKET_SUCCESS = 'REOPEN_TICKET_SUCCESS';
export const REOPEN_TICKET_FAIL = 'REOPEN_TICKET_FAIL';


export const REASSIGN_TICKET_START = 'REASSIGN_TICKET_START';
export const REASSIGN_TICKET_SUCCESS = 'REASSIGN_TICKET_SUCCESS';
export const REASSIGN_TICKET_FAIL = 'REASSIGN_TICKET_FAIL';
export const ASSIGN_TICKET_START = 'ASSIGN_TICKET_START';
export const ASSIGN_TICKET_SUCCESS = 'ASSIGN_TICKET_SUCCESS';
export const ASSIGN_TICKET_FAIL = 'ASSIGN_TICKET_FAIL';
export const REASSIGN_REOPENED_TICKET_START = 'REASSIGN_REOPENED_TICKET_START';
export const REASSIGN_REOPENED_TICKET_SUCCESS = 'REASSIGN_REOPENED_TICKET_SUCCESS';
export const REASSIGN_REOPENED_TICKET_FAIL = 'REASSIGN_REOPENED_TICKET_FAIL';








