# Generated by Django 3.0.7 on 2021-01-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201227_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='inactive', max_length=123),
        ),
        migrations.AlterField(
            model_name='interestbearingaccount',
            name='active',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='inactive', max_length=123),
        ),
    ]
