# Generated by Django 3.1.4 on 2020-12-27 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=68)),
                ('type', models.CharField(choices=[('school', 'ENTIRE SCHOOL'), ('klass', 'CERTAIN CLASS'), ('student', 'INDIVIDUAL STUDENT')], max_length=200)),
                ('status', models.CharField(choices=[('published', 'PUBLISHED'), ('draft', 'DRAFT'), ('cancelled', 'CANCELLED')], max_length=200)),
                ('date_created', models.DateField()),
                ('expiry_date', models.DateField()),
                ('content', models.TextField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculums', to='setup.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=68)),
                ('type', models.CharField(choices=[('school', 'ENTIRE SCHOOL'), ('klass', 'CERTAIN CLASS'), ('student', 'INDIVIDUAL STUDENT')], max_length=200)),
                ('status', models.CharField(choices=[('published', 'PUBLISHED'), ('draft', 'DRAFT'), ('cancelled', 'CANCELLED')], max_length=200)),
                ('date_created', models.DateField()),
                ('expiry_date', models.DateField()),
                ('content', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
