# Generated by Django 3.1.5 on 2021-02-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=68)),
                ('type', models.CharField(choices=[('school', 'ENTIRE SCHOOL'), ('klass', 'CERTAIN CLASS'), ('student', 'INDIVIDUAL STUDENT')], max_length=200)),
                ('status', models.CharField(choices=[('published', 'PUBLISHED'), ('draft', 'DRAFT'), ('cancelled', 'CANCELLED')], max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
