# Generated by Django 3.1.5 on 2021-01-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='expiry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
