# Generated by Django 3.0.7 on 2021-01-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='school',
        ),
    ]
