# Generated by Django 3.0.7 on 2020-11-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('courses', '0001_initial'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='people.Student'),
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='people.Student'),
        ),
        migrations.AddField(
            model_name='referrencesource',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='courses.Author'),
        ),
        migrations.AddField(
            model_name='referrencesource',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refferences', to='courses.Publisher'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishers', to='courses.PublisherCity'),
        ),
        migrations.AddField(
            model_name='course',
            name='owners',
            field=models.ManyToManyField(related_name='owned_courses', through='courses.AddCourseToSchool', to='setup.Institution'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='courses.StudentCourseEnrollment', to='people.Student'),
        ),
        migrations.AddField(
            model_name='addvideotonote',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.StudyNote'),
        ),
        migrations.AddField(
            model_name='addvideotonote',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Video'),
        ),
        migrations.AddField(
            model_name='addtopicobjective',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.TopicObjective'),
        ),
        migrations.AddField(
            model_name='addtopicobjective',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Topic'),
        ),
        migrations.AddField(
            model_name='addtopicguideline',
            name='guideline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.TopicGuideLine'),
        ),
        migrations.AddField(
            model_name='addtopicguideline',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Topic'),
        ),
        migrations.AddField(
            model_name='addtexttonote',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.StudyNote'),
        ),
        migrations.AddField(
            model_name='addtexttonote',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Text'),
        ),
        migrations.AddField(
            model_name='addimagetonote',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Image'),
        ),
        migrations.AddField(
            model_name='addimagetonote',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.StudyNote'),
        ),
        migrations.AddField(
            model_name='addfiletonote',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Text'),
        ),
        migrations.AddField(
            model_name='addfiletonote',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.StudyNote'),
        ),
        migrations.AddField(
            model_name='addcoursetoschool',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='addcoursetoschool',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='setup.Institution'),
        ),
        migrations.AddField(
            model_name='addbibliography',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.StudyNote'),
        ),
        migrations.AddField(
            model_name='addbibliography',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.ReferrenceSource'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourseenrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='addvideotonote',
            unique_together={('note', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='addtopicobjective',
            unique_together={('objective', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='addtopicguideline',
            unique_together={('guideline', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='addtexttonote',
            unique_together={('note', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='addimagetonote',
            unique_together={('note', 'image')},
        ),
        migrations.AlterUniqueTogether(
            name='addfiletonote',
            unique_together={('note', 'file')},
        ),
        migrations.AlterUniqueTogether(
            name='addcoursetoschool',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='addbibliography',
            unique_together={('note', 'reference')},
        ),
    ]
