# Generated by Django 3.0.7 on 2020-11-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201126_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrencesource',
            name='date_published',
            field=models.DateField(),
        ),
    ]
