# Generated by Django 3.1.5 on 2021-01-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210125_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owners',
        ),
    ]
