# Generated by Django 3.0.7 on 2020-11-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('courses', '0003_auto_20201126_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='bibliography',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_visibility',
            field=models.CharField(choices=[('show', 'SHOW'), ('hide', 'HIDE')], max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='taken_courses', through='courses.StudentCourseEnrollment', to='people.Student'),
        ),
    ]
