# Generated by Django 3.0.7 on 2020-11-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_layout',
        ),
        migrations.RemoveField(
            model_name='course',
            name='default_grouping',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enable_completion_tracking',
        ),
        migrations.RemoveField(
            model_name='course',
            name='force_group_mode',
        ),
        migrations.RemoveField(
            model_name='course',
            name='force_language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='group_mode',
        ),
        migrations.RemoveField(
            model_name='course',
            name='hidden_sections',
        ),
        migrations.RemoveField(
            model_name='course',
            name='maximum_upload_size',
        ),
        migrations.RemoveField(
            model_name='course',
            name='number_of_announcements',
        ),
        migrations.RemoveField(
            model_name='course',
            name='number_of_sections',
        ),
        migrations.RemoveField(
            model_name='course',
            name='show_activity_reports',
        ),
        migrations.RemoveField(
            model_name='course',
            name='show_gradebook_to_students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='topics_format',
        ),
        migrations.RemoveField(
            model_name='course',
            name='your_word_for_administrator',
        ),
        migrations.RemoveField(
            model_name='course',
            name='your_word_for_authenticated_user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='your_word_for_course_creator',
        ),
        migrations.RemoveField(
            model_name='course',
            name='your_word_for_course_designer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='your_word_for_guest',
        ),
        migrations.RemoveField(
            model_name='course',
            name='your_word_for_manager',
        ),
        migrations.RemoveField(
            model_name='course',
            name='your_word_for_non_editing_teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='your_word_for_parent',
        ),
        migrations.RemoveField(
            model_name='course',
            name='your_word_for_student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='your_word_for_teacher',
        ),
    ]
