# Generated by Django 3.1.5 on 2021-02-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210202_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtopicobjective',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
