# Generated by Django 3.0.7 on 2020-11-26 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20201126_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynote',
            name='files',
            field=models.ManyToManyField(through='courses.AddFileToNote', to='courses.File'),
        ),
        migrations.AddField(
            model_name='studynote',
            name='images',
            field=models.ManyToManyField(through='courses.AddImageToNote', to='courses.Image'),
        ),
        migrations.AddField(
            model_name='studynote',
            name='notes',
            field=models.ManyToManyField(through='courses.AddTextToNote', to='courses.Text'),
        ),
        migrations.AddField(
            model_name='studynote',
            name='references',
            field=models.ManyToManyField(through='courses.AddBibliography', to='courses.ReferrenceSource'),
        ),
        migrations.AddField(
            model_name='studynote',
            name='videos',
            field=models.ManyToManyField(through='courses.AddVideoToNote', to='courses.Video'),
        ),
        migrations.AlterField(
            model_name='addfiletonote',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.File'),
        ),
    ]
