# Generated by Django 3.1.5 on 2021-02-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_addtopicobjective_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtopicobjective',
            name='course_id',
        ),
        migrations.AddField(
            model_name='topic',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
