# Generated by Django 3.1.5 on 2021-02-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210202_1514'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addfiletonote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='addfiletonote',
            name='file',
        ),
        migrations.RemoveField(
            model_name='addfiletonote',
            name='note',
        ),
        migrations.AlterUniqueTogether(
            name='addimagetonote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='addimagetonote',
            name='image',
        ),
        migrations.RemoveField(
            model_name='addimagetonote',
            name='note',
        ),
        migrations.AlterUniqueTogether(
            name='addtexttonote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='addtexttonote',
            name='note',
        ),
        migrations.RemoveField(
            model_name='addtexttonote',
            name='text',
        ),
        migrations.AlterUniqueTogether(
            name='addvideotonote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='addvideotonote',
            name='note',
        ),
        migrations.RemoveField(
            model_name='addvideotonote',
            name='video',
        ),
        migrations.DeleteModel(
            name='AddBibliography',
        ),
        migrations.DeleteModel(
            name='AddFileToNote',
        ),
        migrations.DeleteModel(
            name='AddImageToNote',
        ),
        migrations.DeleteModel(
            name='AddTextToNote',
        ),
        migrations.DeleteModel(
            name='AddVideoToNote',
        ),
    ]
