# Generated by Django 3.1.5 on 2021-02-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210202_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_visibility',
        ),
    ]
