# Generated by Django 3.1.5 on 2021-02-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_course_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='course',
            name='stream',
        ),
    ]
