# Generated by Django 3.1.5 on 2021-02-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('courses', '0013_auto_20210206_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='amastudents',
            field=models.ManyToManyField(blank=True, related_name='taken_courses', through='courses.StudentCourseEnrollment', to='people.StudentProfile'),
        ),
        migrations.DeleteModel(
            name='AddCourseToSchool',
        ),
    ]
