# Generated by Django 3.1.5 on 2021-02-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210208_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourseenrollment',
            name='final_grade',
        ),
    ]
