# Generated by Django 3.1.5 on 2021-02-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_studentcourseenrollment_final_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
