# Generated by Django 3.1.5 on 2021-06-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20210308_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
                ('slide', models.FileField(upload_to='slides/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'ACTIVE')], default='active', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='slides',
            field=models.ManyToManyField(blank=True, to='courses.LessonSlide'),
        ),
    ]
