# Generated by Django 3.1.5 on 2021-06-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20210611_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonslide',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
