# Generated by Django 3.1.5 on 2021-06-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_lessonslide_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonslide',
            name='date',
        ),
    ]
