# Generated by Django 3.1.5 on 2021-06-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_lessonslide_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonslide',
            name='slide',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
