# Generated by Django 3.0.7 on 2020-11-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('klasses', '0001_initial'),
        ('grading', '0001_initial'),
        ('courses', '0002_auto_20201126_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='people.Student'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='grading.CourseGrade'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_grades', to='people.Student'),
        ),
        migrations.AddField(
            model_name='generalgrade',
            name='klass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ongoing_grades', to='klasses.StudentClass'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='klass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ongoing_course_grades', to='klasses.StudentClass'),
        ),
    ]
