# Generated by Django 3.1.5 on 2021-01-26 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210125_1401'),
        ('grading', '0002_auto_20210125_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='people.studentprofile'),
        ),
    ]
