# Generated by Django 3.0.7 on 2020-12-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('curriculum', '0002_auto_20201227_0837'),
        ('grading', '0002_auto_20201227_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalgrade',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marklist', to='people.StaffUser'),
        ),
        migrations.AddField(
            model_name='generalgrade',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.Subject'),
        ),
    ]
