# Generated by Django 3.1.5 on 2021-01-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_auto_20210126_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalgrade',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
