# Generated by Django 3.0.7 on 2020-11-26 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=355, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(choices=[('sir', 'SIR'), ('miss', 'MISS'), ('mr', 'MR'), ('mrs', 'MRS'), ('doc', 'Doctor'), ('prof', 'Proffesor')], max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=500, null=True)),
                ('id_number', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=16, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=16, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('people.user',),
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(choices=[('sir', 'SIR'), ('miss', 'MISS'), ('mr', 'MR'), ('mrs', 'MRS'), ('doc', 'Doctor'), ('prof', 'Proffesor')], max_length=200)),
                ('id_number', models.CharField(blank=True, max_length=64, null=True)),
                ('category', models.CharField(choices=[('admin', 'School Admin'), ('teacher', 'Teacher'), ('librarian', 'Librarian'), ('clerk', 'Clerk'), ('it_admin', 'IT Admin'), ('hofad', 'Head Office Admin')], max_length=341)),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=16, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=16, unique=True)),
                ('employee_number', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('people.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=500, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=16, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=16, unique=True)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='people.Parent')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='setup.Institution')),
            ],
            options={
                'abstract': False,
            },
            bases=('people.user',),
        ),
    ]
