# Generated by Django 3.0.7 on 2020-11-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20201129_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('admin', 'School Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('librarian', 'Librarian'), ('clerk', 'Clerk'), ('it_admin', 'IT Admin'), ('hofad', 'Head Office Admin')], default='student', max_length=341),
        ),
    ]
