# Generated by Django 3.2.4 on 2021-08-21 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_userpasswordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpasswordresetcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resetters', to=settings.AUTH_USER_MODEL),
        ),
    ]
