# Generated by Django 3.0.7 on 2020-11-29 11:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20201129_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
