# Generated by Django 3.2.4 on 2021-08-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_userpasswordresetcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasswordresetcode',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpasswordresetcode',
            name='uses',
            field=models.IntegerField(default=0),
        ),
    ]
