# Generated by Django 3.0.7 on 2021-01-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('klasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='klasses.StudentClass'),
        ),
    ]
