# Generated by Django 3.0.7 on 2021-01-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0002_admission_klass'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='people.StudentProfile'),
        ),
    ]
