# Generated by Django 3.1.5 on 2021-01-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_admission_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='application_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
