# Generated by Django 3.0.7 on 2020-12-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('enrollment', '0003_admission_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='people.Student'),
        ),
    ]
