# Generated by Django 3.1.5 on 2021-07-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExitProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('longevity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseoffered',
            name='content',
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'ONGOING'), ('upcoming', 'UPCOMING'), ('finished', 'FINISHED')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='exit_profiles',
            field=models.ManyToManyField(blank=True, to='adverts.CourseObjective'),
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='topics',
            field=models.ManyToManyField(blank=True, to='adverts.CourseTopic'),
        ),
    ]
