# Generated by Django 3.1.5 on 2021-07-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20210729_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexitprofile',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseobjective',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
