# Generated by Django 3.1.5 on 2021-08-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_auto_20210729_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffered',
            name='objectives',
            field=models.ManyToManyField(blank=True, to='adverts.CourseObjective'),
        ),
        migrations.AlterField(
            model_name='courseoffered',
            name='exit_profiles',
            field=models.ManyToManyField(blank=True, to='adverts.CourseExitProfile'),
        ),
    ]
