# Generated by Django 3.2.4 on 2021-08-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_auto_20210820_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffered',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
