# Generated by Django 3.0.7 on 2021-01-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20210125_0958'),
        ('curriculum', '0001_initial'),
        ('klasses', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstudysubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studentstudysubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.Subject'),
        ),
        migrations.AddField(
            model_name='klassstudiedsubject',
            name='courses',
            field=models.ManyToManyField(related_name='subject', through='curriculum.AddCourseToSubject', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='klassstudiedsubject',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klasses.StudentClass'),
        ),
        migrations.AddField(
            model_name='klassstudiedsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.Subject'),
        ),
        migrations.AddField(
            model_name='klassstudiedsubject',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_subjects', to='people.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='addcoursetosubject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='addcoursetosubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.KlassStudiedSubject'),
        ),
        migrations.AlterUniqueTogether(
            name='studentstudysubject',
            unique_together={('student', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='klassstudiedsubject',
            unique_together={('klass', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='addcoursetosubject',
            unique_together={('course', 'subject')},
        ),
    ]
