# Generated by Django 3.2.4 on 2021-08-04 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('enquiry', 'ENQUIRY'), ('complaint', 'COMPLAINT'), ('refund', 'REFUND'), ('application', 'APPLICATION'), ('payment', 'PAYMENT'), ('order', 'ORDER')], default='enquiry', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reopened', 'Reopened'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=200)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low'), ('very_low', 'Very Low')], default='normal', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickects', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handled_tickects', to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(blank=True, to='tickets.Comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
