# Generated by Django 3.2.4 on 2021-08-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('reopened', 'Reopened'), ('closed', 'Closed')], default='open', max_length=200),
        ),
    ]
